# Site settings
title: Aayush Tuladhar
email: aayush.tuladhar@gmail.com
description: >
  Hi, I'm Aayush! Here, I write on topics related to programming, development, open source and anything related to my line of work.
baseurl: ""
url: "http://www.aayushtuladhar.com/jekyll_site_template"
twitter_username:
github_username:  arttuladhar